#!/bin/bash

APP_NAME=no-bs
APP_LOCATION="/opt/${APP_NAME}"
LOGS=/var/log/${APP_NAME}
PID_FILE="/var/run/${APP_NAME}.pid"

case "$1" in
  start)
    echo "Starting No BS..."
    nohup java -jar "${APP_LOCATION}/${APP_NAME}.jar" &
    PID=$!
    echo "Started app with PID: ${PID} in ${PID_FILE}"
    sudo touch ${PID_FILE}
    sudo echo -e "${PID}" | sudo tee ${PID_FILE}
    ;;
  stop)
    echo "Stopping No BS..."
    PID=`cat ${PID_FILE}`
    echo "Stopping app running with ${PID}"
    test -z $PID || kill $PID
    ;;
esac
